#登陆页面国际化需要配置这个


spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/hengsu
        #url: jdbc:mysql://192.168.10.160:3306/smelt
        username: root
       # password: voidstar
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        max-active: 20
        initialSize: 1
        max-wait: 60000
        min-idle: 1
        max-idle: 5
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

    redis:
        database: 0
        host: localhost
        port: 6379
        password:
        pool:
            max-active: 8
            max-wait: 120
            max-idle: 8
            min-idle: 0
        timeout: 0
    messages:    ##登陆页面国际化需要配置这个
        basename: i18n.login


mybatis:
    mapper-locations: classpath:mybatis/mapper/*.xml
    type-aliases-package: com.voidstar.base.entity